---
 - hosts: all
   become: yes
   tasks:
     - name: Get CPU and memory information
       ansible.builtin.setup:
          filter:
            - 'ansible_distribution'
            - 'ansible_machine_id'
            - 'ansible_*_mb'
          register: system_info
      
     - name: Save system info to file
       ansible.bultin.copy:
       content: |
         {% for host in
            system_info.ansible_facts.keys()  %}
   {{host}}:
 CPU: {{system_info.ansible_facts[host]
        ['processor']}}
RAM: {{system_info.ansible_facts[host]
['memtotal_mb']}} MB
{%endfor%}
dest: /path/file.txt
  
