---
- hosts: all
  become: true
  tasks:
    - name: add user
      user:
        name: ansibleuser2
        password: "{{ lookup('file', '/home/admin/ancible/passwd.txt') }}"
        shell: /bin/bash
        group: wheel
        append: yes

